// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Simcag.ProcessingService.Infrastructure.Persistence;

#nullable disable

namespace Simcag.ProcessingService.Infrastructure.Migrations
{
    [DbContext(typeof(ProcessingDbContext))]
    [Migration("20260531113000_AddSupplierIdentificationConfidenceScore")]
    partial class AddSupplierIdentificationConfidenceScore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Modelo alvo consolidado em ProcessingDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
